### ISSUE TITLE
Faker 2.0 design

### ISSUE THREAD

**Issue by erikgaal** [FakerPHP/Faker#15]
Hey all,

In fzaninotto's repo a discussion was started about the design of the next major version (https://github.com/fzaninotto/Faker/issues/1807). Shall we reopen that here?

The three questions asked by @pimjansen were:
* Which PHP versions will be supported?
* What development tools are to be used?
* What does the actual architecture look like?

**Comment by mathieutu** [comment]
I think @fzaninotto is right saying the package is way to heavy, and should be splitted, with an extract of the languages.

>I'm super concerned about the responsibility that we developers have on climate change. Over the years, Faker has probably emitted more than 11 Metric tons of CO2 equivalent. Being such a significant contributor to climate change kills me.
>
>Most people only use 1 locale, so they only need a fraction of the library size. Yet, because it's designed as a multilingual library, there is no alternative: they have to download the 3MB even if they only need 10KB.
>
>Faker should have been a small core library with no localized content. Then, developers from all over the world would have contributed localized packages to packagist, without requiring my supervision for merges. And users would just have to download the core and the locale they need.

With this organisation it could be easier to maintain separatly locale providers.

**Comment by erikgaal** [comment]
Do we want to split Faker and its locales into different repositories, or do we want to keep a single repo and split it into different Composer packages (like `laravel/framework` does with `illuminate/*`)? For the end user they achieve the same thing: smaller, composable packages. So the choice here has to be made in favour of the developer experience.

Monorepo:
* 👍 Easier to work on the entire project.
* ...?

Multirepo:
* 👍 Easier to work on a single locale.
* 👎 Might result in outdated locales, if they are not upgrades simultaneously.
* ...?

**Comment by mfn** [comment]
I think Laravel and Symfony are successful examples of such monorepos, using read-only repos for splitting/releasing (no issues there, for example).

I think a single repo for just for the issues is already better than having it spread and worst-case having issues in wrong repos.

I'm 👍 mono-repo if the split happens, because I figure you want to run the test suite also with all of them and that's why certain things are "just easier" and there's only the one-time complexity of setting everything up and making it work (with scripts).

**Comment by darthsoup** [comment]
I also believe that the Monorepo is the best approach for this project, just like Laravel does.

**Comment by erikgaal** [comment]
Do we want to use a democratic system (using something like https://github.com/apex/gh-polls) to make the decisions here?

**Comment by mathieutu** [comment]
In my opinion, shared issues and pull request are here an inconvenient, instead of an advantage.

We're not talking about splitting a framework in different packages but having N independent locales which should evolve differently (respecting common interfaces, of course).

One of the pain point François raised is maintaining those locales, while not understanding the language.

With several repos, we can have different repo maintainers who are responsible for their own locale. It will so be easier to maintain the whole thing. 

And it'll also be easier to find maintainers: if I have no time and no envy to maintain faker, I'm totally OK with handling the French locale, because smaller project, less and clearer notifications, and _less responsibility_.

Thoughts?

**Comment by ytilotti** [comment]
I agree with @mathieutu. It makes more sense to create differents repositories with differents mainteners. It's like in the translation business, you can only translate into your native language. It is not possible to manage languages that you can't understand.

A repository locale list on this repository would be consistent.

**Comment by mbabker** [comment]
Hi, some opinions from random onlooker who also recently went through the monorepo versus manyrepo debate.

So, I recently restructured [Pagerfanta](https://github.com/BabDev/Pagerfanta) to support installing different optional elements as separate packages (akin to `illuminate/*` versus `laravel/framework` or `symfony/*` versus `symfony/symfony`).  Part of my thinking in how I approached it is that if a portion of the monorepo gets deprecated in any way, [all of the subsplit repos](https://github.com/pagerfanta-packages) remain available and could be forked or become a canonical point of truth if someone were to want to become a maintainer for an individual package.

So, if I were a maintainer here, what I would personally do to start off is go with the monorepo approach while keeping all of the locales within this repo and supporting a subsplit, then if I found it to be too busy supporting those in one repo, in theory it should not take too much effort to turn the split locale repo into the point of truth and drop that portion of the code from the main repository.

**Comment by mathieutu** [comment]
>if I found it to be too busy supporting those in one repo

Actually, in the faker context, we do have years of experience and [feedback](https://marmelab.com/blog/2020/10/21/sunsetting-faker.html#faker-is-a-curse) on it: 
>These PRs were in a language I don't speak, so I had no way of knowing whether the data was good or bad. I ended up closing many PRs for copyright reasons and blindingly merging the others.

**Comment by mbabker** [comment]
Right, but wasn't the original repo predominantly a single person overseeing things?  There's a team here, so presumably one could use the code owners feature of GitHub to request reviews from team members who are "language specialists" (for lack of better terms) instead of expecting an English speaker to review all non-English changes.  It wouldn't be much different than having those same team members review and merge pull requests to other repos other than the amount of traffic/noise on a single repository.

**Comment by pimjansen** [comment]
Im a fan to keep things seperate as much as possible. Where a mono repo is really cool but that is not the only thing. We always talk about Locale and stuff like that but Faker also holds so called Providers. Technically it is the same thing but the providers hold non language specific things.

For example there is an eCommerce provider as a suggestion. This provider will probably never make it to the Faker core but it should be easy to be pluggable.

I think if we provider proper interfaces for the locales we can ensure that the quality of those locales are good and that they hold all the required data.

**Comment by Nyholm** [comment]
This is an interesting discussion. I am a big fan of mono repos. I would say mono repo 7 days every week. However @mathieutu makes a really good point. 

Since we have localized providers, we have a really hard time figuring out what is a good PR or not. I dont believe any of you could properly verify [this PR to add Swedish municipalities](#30). 

I vote for doing separated repositories. I also think that if someone contributes we should make them a maintainer to that repository. Let's aim for at least 2-3 maintainers per locale.

**Comment by Bavragor** [comment]
I already started splitting up faker into faker-core, and one repository for each locale, also planned to add some more for ORM etc.

Like nyholm said, I also strongly believe that separate repositories are necessary to maintain language specific providers.

**Comment by pimjansen** [comment]
> I already started splitting up faker into faker-core, and one repository for each locale, also planned to add some more for ORM etc.
> 
> Like nyholm said, I also strongly believe that separate repositories are necessary to maintain language specific providers.

I think it is important first to discuss on what to take into the core and define the interfaces on what we think is best. Same goes for the interface on the outside so that we can keep an easy migration plan available.

Graham already mentioned it earlier which i believe was totally right, that we need to use 2020 to ensure people migrate to the new repository and continue to support it. If we start breaking all stuff people will probably not move. Where also the old repo is still there and working fine for those

**Comment by stevebaros** [comment]
Small Isolated and localized packages would be the best Fit, The core Faker Framework should stand alone as a package Maintained by the core team. Core Team **should give visibility** to well crafted localized packages.

**Comment by Nyholm** [comment]
👍 

I imagine the current fakerphp/faker to be the “core package” with the English translations. Most people will only install that.

**Comment by pimjansen** [comment]
> 👍 
> 
> I imagine the current fakerphp/faker to be the “core package” with the English translations. Most people will only install that. 

Even the english could go in a seperate package but with an hard require from core.

The reason why is that it could help people with a nice starting point while building their own instead of figuring out from core what they need.

Since the more locales the more complete it will be

**Comment by LucaRed** [comment]
I'm in favor of separating the core package and the localized versions. 👍 A stand-alone English package would be a great starting point for new localizations.

Like @mathieutu said for the French locale, my software company would be very glad to mantain the Italian localization.

**Comment by JoshuaLuckers** [comment]
I wouldn’t mind maintaining the Dutch locale!

**Comment by devfaysal** [comment]
It would be really nice to seperate the locale.
I would love to manage bn_BD nad en_BD
Here is my fork for en_BD https://github.com/devfaysal/faker
The main repo was feeeze for adding a new locale, so couldn't get a chance to make the PR.

**Comment by winkbrace** [comment]
Really cool to see this design direction considering the worries of fzaninotto. Thanks for picking this library up, guys. I worked with mono and many repos and in the end it doesn't matter much which you pick as long as you stick to the same interface contracts. When a project is new and likely to change, I'd go with monorepo and when it's stabilized the many repo becomes slightly preferred.

**Comment by claudsonm** [comment]
Let's take the multi repository approach. The thing is: should those repositories be under the fakerphp organization? The [Laravel Notification Channels](https://laravel-notification-channels.com/) works like that and it's very successful.

I'm the maintainer of the AWS SNS channel. The only thing I see that still could bothers the core maintainers, is when some update is needed and they have to open issues in every repository asking for the changes needed. It's not such a big deal, but in general, I think we can agree that the is approach is going super fine.

**Comment by GrahamCampbell** [comment]
You know, something we could do is make this a monorepo, and have subsplits for each locale. It might make things easier to maintain. @Nyholm has a lot of experience with this (in particular, I'm thinking about the async aws).

**Comment by pimjansen** [comment]
> You know, something we could do is make this a monorepo, and have subsplits for each locale. It might make things easier to maintain. @Nyholm has a lot of experience with this (in particular, I'm thinking about the async aws).

He already indicated that mono repo wont work here where you still have no clue on what to merge where and if its good or not since you cant just a chinese locale for instance.

But maybe it is time to start a new discussion. If we split things off i suggest that we also think about things that belong in core and which do not.

In my opinion these are things that need to go

* ORM integration. The reason why is that it requires more ORM knowledge and has not that much todo with Faker itself
* Ofcourse the locales itself where we can add a require to the english locale as default. Yes it means everyone uses it also if you do not want it but i assume it is like 99.x% that needs it
* We remove the image integration. I'd rather have it as seperate package where it now uses an external service. We could generate our own but that would mean that Faker will require stuff like GD which i dont think is good. As a package the module is a choice of the user instead.

I think one of the next steps is to think about what is the core. We have a few good providers like
* Person
* Date
* etc

We need to start listing this and define interfaces though

**Comment by fangmuke** [comment]
Have you overlooked a problem, didn't you just use faker in development? When developing a new site, it may not only target a certain country...isn’t it? So I support monorepo!

**Comment by IonBazan** [comment]
Another advantage of monorepo I see is when someone wants to introduce a new locale, they simply open a new PR in the main repository with all needed files/logic while in multirepo approach that would start with an issue and require organization owner to create a new repository, find a maintainer for it, wait for initial PRs, etc.
Monorepo makes it easier to write tests too as you can reuse generic test code from the core.
Multirepo, on the other hand, makes it easier to test against multiple versions of other libraries/integrations (ORMs, frameworks, etc).
That's why I would propose to keep locales in monorepo and use `CODEOWNERS` file to assign reviewers while splitting any integrations (frameworks, ORMs, external services) to separate repositories.

**Comment by bramceulemans** [comment]
> Monorepo makes it easier to write tests too as you can reuse generic test code from the core.

This is also possible with multi-repo.

---

Personally I think it will be cleaner to split locales off to separate repo's, that way there they can have their own maintainers. I'm already looking at some PR's right now, having no clue if any of the specifications used are correct.

It will be good to build a strong core package, with interfaces, that locales can extend.

**Comment by pattisahusiwa** [comment]
Hello all.

I'd love to maintain `id_ID` locale. Thank you for keeping this library alive.

**Comment by joelharkes** [comment]
Would it be possible to abstract the random generation from the actual implementation:

the random generation could be a siple interface:
```php
interface Random {
 nextByte(): int;
}
```

the nice thing would be user could provide his own random generator, but still use the rest of the faker library.

there is a whole bunch of different algorithms the user could use: https://en.wikipedia.org/wiki/List_of_random_number_generators

**Comment by emiliopedrollo** [comment]
> Another advantage of monorepo I see is when someone wants to introduce a new locale, they simply open a new PR in the main repository with all needed files/logic while in multirepo approach that would start with an issue and require organization owner to create a new repository, find a maintainer for it, wait for initial PRs, etc.

Nothing prevents a developer from creating it's own language package using multirepo and then handing over to FakerPHP org.

**Comment by emiliopedrollo** [comment]
> Have you overlooked a problem, didn't you just use faker in development? When developing a new site, it may not only target a certain country...isn’t it? So I support monorepo!

I don't tink so. My company works with 3 locales for now, way less than 70+ that Faker provides, and I think it's the case for most projects. And if you really must you can require all as dependencies.

**Comment by pimjansen** [comment]
> Would it be possible to abstract the random generation from the actual implementation:
> 
> the random generation could be a siple interface:
> ```php
> interface Random {
>  nextByte(): int;
> }
> ```
> 
> the nice thing would be user could provide his own random generator, but still use the rest of the faker library.
> 
> there is a whole bunch of different algorithms the user could use: https://en.wikipedia.org/wiki/List_of_random_number_generators
> 
> a provider could than base its picking on which data to use based on this interface.

I dont think we will do it right away though but i understand the idea.

We could later set it via a setter on the instance i assume or always use a customer extension for it

**Comment by bramceulemans** [comment]
> We could later set it via a setter on the instance i assume or always use a customer extension for it

Actually @Nyholm and myself had a discussion the other day, and he brought up the idea of using a PSR-11 container.

When constructing Faker:

Register your extension with PSR-11:
```php
use Faker\Factory;
 
$builder = new ContainerBuilder();
$builder->register(Foo:class);
$container = $builder->build();

$faker = Factory::create(null, $container);
```

First paremeter is the locale implementing or null, second is an optional dependency container.

**Comment by bambamboole** [comment]
It would be an honor to maintain the de_DE locale of fakerPHP. So if there is some need just shout out :)

**Comment by emiliopedrollo** [comment]
I could maintain the pt_BR locale as well

**Comment by javabudd** [comment]
please god split this up into a repo for each provider and let someone/s own it

**Comment by pimjansen** [comment]
> please god split this up into a repo for each provider and let someone/s own it

This is an option but also grouping it for certain languages. For instance.

Nl_NL
Nl_BE

etc

**Comment by Nyholm** [comment]
Hey. 
I’ve drafted some ideas of an architecture. Feel free to add comments or suggest changes with a or. 

https://github.com/Nyholm/next-faker
