### ISSUE TITLE
e164PhoneNumber() generates invalid US Phone Numbers

### ISSUE THREAD

**Issue by RPJamie** [FakerPHP/Faker#332]
### Summary

Using `e164PhoneNumber()`, an invalid number is created for en_US. The generated phone numbers that start with 0 or 1, are invalid.

### Versions

|                | Version |
|:---------------|:--------|
| PHP            | 8.0   |
| `fakerphp/faker`  | 1.14.1   |

### Self-enclosed code snippet for reproduction

```php
 $faker = FakerFactory::create();

dump($faker->e164PhoneNumber());
```

Example invalid number that was generated: `+16200858074`

Tested using giggsey/libphonenumber-for-php library locally as well as the online version
https://giggsey.com/libphonenumber/index.php?phonenumber=%2B16200858074&country=US //Starting with 0
https://giggsey.com/libphonenumber/index.php?phonenumber=%2B16201858074&country=US //Starting with 1

both `isValidNumber()` and `isValidNumberForRegion()` fail

**Comment by bramceulemans** [comment]
I'm not sure I understand, from my understanding phone numbers can start with a `+` followed by a country code.

**Comment by IonBazan** [comment]
@RPJamie @bramceulemans According to [Wikipedia](https://en.wikipedia.org/wiki/North_American_Numbering_Plan#Modern_plan), +16200858074 is invalid because `085` is an invalid Central Office code - they may not start with `0` or `1`. What is more, the last 2 digits of Central Office code may not be `11`. These rules raise the complexity of E164 number faking dramatically and personally I don't think it's worth keeping it 100% compliant but PRs are welcome 😉

**Comment by miken32** [comment]
@IonBazan this is a simple check and anyway the code is already in place. In `Faker\Provider\en_US\PhoneNumber` simply change the format string to include the exchange code placeholder.
```php
$e164Formats = [
        '+1{{areaCode}}{{exchangeCode}}####',
];
```
