### ISSUE TITLE
Formatters are not reset when adding a new provider

### ISSUE THREAD

**Issue by singleseeker** [FakerPHP/Faker#366]
### Summary

After using addProvider  method, get a weird result

### Versions

|                | Version |
|:---------------|:--------|
| PHP            |  7.4.13   |
| `fakerphp/faker`  | 1.15.0  |

```php

use Faker\Provider\en_US\Person;
use Faker\Provider\zh_CN\Person as Zh_CNPerson;

// =============================

$this->faker->addProvider(new Person($this->faker));

dump($this->faker->lastName() . ' ' . $this->faker->firstName());

$this->faker->addProvider(new Zh_CNPerson($this->faker));

dd($this->faker->lastName() . ' ' . $this->faker->firstName());
```

sometimes, you may hope to use different names, with addProvider method, get a weird result.

```text
"Kerluke Lexie"
"Turner 杨"
```

**Comment by bram-pkg** [comment]
What happens when you run this multiple times?

**Comment by aanfarhan** [comment]
@singleseeker 
I think this happened because when you addProvider it's not replace the previous provider but it append the new one, so it would generate randomly using the existing providers, which in your case (en_US\Person & zh_CN\Person).
If you want to use different locale provider maybe you can create new instance of faker with the locale provider that you want.

For example:
```php
$faker1 = Faker\Factory::create('zh_CN');
echo $faker1->lastName(). ' '.$faker1->firstName().PHP_EOL; // this will print last name & first name using zh_CN\Person provider.

$faker2 = Faker\Factory::create();
echo $faker2->lastName(). ' '.$faker2->firstName().PHP_EOL; // this will print last name & first name using default locale provider en_US\Person.
```
