### ISSUE TITLE
[v2.0] Rename Factory class

### ISSUE THREAD

**Issue by pattisahusiwa** [FakerPHP/Faker#60]
I think `Factory` class name is too generic. Please consider renaming the class to e.q `FakerFactory`.

**Comment by bramceulemans** [comment]
We actually had a discussion about getting rid of the `Factory` all together and just using a constructor.

**Comment by pattisahusiwa** [comment]
That's even better. Are you planning to split `Generator` class into smaller classes and get rid of all magic properties and methods?

**Comment by pimjansen** [comment]
@pattisahusiwa see the discussion on the issue tracker and feel free to contribute to the discussion. We are not use how to handle the generators actually.

Concerning all the magic we are having some directions to split two topics on Faker.  This means we will have a clean split on core methods (without magic) and extensions.

However locale specific items will always hold some kind of magic since we can not add them to the generic interface.

**Comment by pimjansen** [comment]
Im closing this issue. If more discussion is needed please use #15
